# Generated by Django 3.2.11 on 2022-01-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=3, verbose_name='Kod języka')),
                ('name', models.CharField(blank=True, default='', max_length=60, verbose_name='Nazwa języka')),
                ('native', models.CharField(blank=True, default='', max_length=60, verbose_name='Język rdzenny')),
            ],
            options={
                'verbose_name': 'Język',
                'verbose_name_plural': 'Języki',
            },
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=39, unique=True, verbose_name='Adres IP')),
                ('continent_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Nazwa kontynentu')),
                ('country_name', models.CharField(blank=True, default='', max_length=56, verbose_name='Nazwa kraju')),
                ('region_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nazwa regionu')),
                ('city', models.CharField(blank=True, default='', max_length=200, verbose_name='Miasto')),
                ('zip', models.CharField(blank=True, default='', max_length=10, verbose_name='Kod pocztowy')),
                ('latitude', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='Szerokość geograficzna')),
                ('longitude', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='Wysokość geograficzna')),
                ('languages', models.ManyToManyField(blank=True, related_name='related_geolocations', to='geolocations.Language', verbose_name='Język/Języki')),
            ],
            options={
                'verbose_name': 'Geolokalizacja',
                'verbose_name_plural': 'Geolokalizacje',
            },
        ),
    ]
